/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Clientes: typeof import('./components/Clientes.vue')['default']
    Facturas: typeof import('./components/Facturas.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    NFactura: typeof import('./components/NFactura.vue')['default']
    NPoliza: typeof import('./components/NPoliza.vue')['default']
    NTecnico: typeof import('./components/NTecnico.vue')['default']
    Poliza: typeof import('./components/NPoliza.vue')['default']
    Polizas: typeof import('./components/Polizas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tecnicos: typeof import('./components/Tecnicos.vue')['default']
  }
}
