/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/clientes': RouteRecordInfo<'/clientes', '/clientes', Record<never, never>, Record<never, never>>,
    '/factura/': RouteRecordInfo<'/factura/', '/factura', Record<never, never>, Record<never, never>>,
    '/factura/[id]': RouteRecordInfo<'/factura/[id]', '/factura/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/facturas': RouteRecordInfo<'/facturas', '/facturas', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/home/[id]': RouteRecordInfo<'/home/[id]', '/home/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/poliza/': RouteRecordInfo<'/poliza/', '/poliza', Record<never, never>, Record<never, never>>,
    '/poliza/[id]': RouteRecordInfo<'/poliza/[id]', '/poliza/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/polizas': RouteRecordInfo<'/polizas', '/polizas', Record<never, never>, Record<never, never>>,
    '/tecnico/': RouteRecordInfo<'/tecnico/', '/tecnico', Record<never, never>, Record<never, never>>,
    '/tecnico/[id]': RouteRecordInfo<'/tecnico/[id]', '/tecnico/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/tecnicos': RouteRecordInfo<'/tecnicos', '/tecnicos', Record<never, never>, Record<never, never>>,
  }
}
